### ISSUE TITLE
Is there an Authentication Strategy Roadmap For Nitro File-Based API?

### ISSUE THREAD

**Issue by twofingerrightclick** [nuxt/nuxt.js#12510]
### Describe the feature

Is there a plan for the addition of route guards to the Nitro API framework? 

I think this could be done in a similar manner to [ `vue-class-component`'s custom decorators](vue-class-component). It would be really cool to add a ` @Auth` or  `@Auth({role: "Admin"})` above a `defineEventHandler()` to take care of the permissions for a handler.

I am transitioning a Nuxt 2 app with an Express API to Nuxt 3, and have noticed that the Nuxt 3 docs do not have examples of authentication, that is the [Nitro File Based API docs](https://nuxt.com/docs/guide/directory-structure/server#server-directory) has no authentication strategies, patterns, or reference to an authentication module that one could use. 
I see some libraries like [@nuxt-alt/auth](https://www.npmjs.com/package/@nuxt-alt/auth) have been adapted, but they are not official, and nor do they support basic auth.
My previous Nuxt 2 app used custom JWT auth. It is a requirement. It appears that the current naive solution is as follows:
1. Create a login endpoint that gives user a JWT.
2. Add a server middleware handler `server/middleware/myAuthHandler.ts` that checks the JWT and sets an appropriate prop on the `event`
3. Given that the server middleware according to the docs cannot cut the request short when auth fails, literally add to each file-based endpoint's 'eventHandler' that requires auth, a check on the `event` (I mean the whole one file per endpoint is tedious enough).

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).
